class AIDetector {
    constructor() {
        this.analyzeBtn = document.getElementById('analyzeBtn');
        this.clearBtn = document.getElementById('clearBtn');
        this.textInput = document.getElementById('textInput');
        this.resultSection = document.getElementById('resultSection');
        this.loadingSection = document.getElementById('loadingSection');
        this.resultContent = document.getElementById('resultContent');

        this.initEventListeners();
    }

    initEventListeners() {
        this.analyzeBtn.addEventListener('click', () => this.analyzeText());
        this.clearBtn.addEventListener('click', () => this.clearText());
        
        this.textInput.addEventListener('input', () => this.validateInput());
    }

    validateInput() {
        const text = this.textInput.value.trim();
        const minLength = 50;
        this.analyzeBtn.disabled = text.length < minLength;
    }

    async analyzeText() {
        const text = this.textInput.value.trim();
        
        if (text.length < 50) {
            alert('Please enter at least 50 characters for analysis.');
            return;
        }

        this.showLoading();
        this.hideResult();

        try {
            const result = await this.callDetectionAPI(text);
            this.displayResult(result);
        } catch (error) {
            this.displayError(error.message);
        } finally {
            this.hideLoading();
        }
    }

    async callDetectionAPI(text) {
        // This will call our Vercel serverless function
        const response = await fetch('/api/detect-ai', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ text })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(errorData.error || 'Failed to analyze text');
        }

        return await response.json();
    }

    displayResult(result) {
        const isAI = result.isAI;
        const confidence = result.confidence;
        
        const confidencePercent = Math.round(confidence * 100);
        
        this.resultContent.innerHTML = `
            <div class="confidence-meter">
                <div class="confidence-fill ${isAI ? 'ai' : 'human'}" 
                     style="width: ${confidencePercent}%"></div>
            </div>
            <div class="result-text ${isAI ? 'ai' : 'human'}">
                ${isAI ? '🤖 AI Generated Content' : '👤 Human Written Content'}
            </div>
            <p>Confidence: <strong>${confidencePercent}%</strong></p>
            <p class="result-description">
                ${isAI ? 
                    'This text appears to be generated by artificial intelligence.' : 
                    'This text appears to be written by a human.'
                }
            </p>
        `;

        this.showResult();
    }

    displayError(message) {
        this.resultContent.innerHTML = `
            <div class="error-message">
                <p style="color: #ff6b6b; font-weight: 600;">Error: ${message}</p>
                <p>Please try again later.</p>
            </div>
        `;
        this.showResult();
    }

    clearText() {
        this.textInput.value = '';
        this.hideResult();
        this.validateInput();
    }

    showLoading() {
        this.loadingSection.classList.remove('hidden');
        this.analyzeBtn.disabled = true;
    }

    hideLoading() {
        this.loadingSection.classList.add('hidden');
        this.validateInput();
    }

    showResult() {
        this.resultSection.classList.remove('hidden');
    }

    hideResult() {
        this.resultSection.classList.add('hidden');
    }
}

// Initialize the application when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    new AIDetector();
});
