// This is a serverless function for Vercel
// Save this as /api/detect-ai.js in your Vercel project

export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { text } = req.body;

        if (!text || text.trim().length < 50) {
            return res.status(400).json({ 
                error: 'Text must be at least 50 characters long' 
            });
        }

        // Get OpenAI API key from environment variables
        const apiKey = process.env.OPENAI_API_KEY;
        
        if (!apiKey) {
            throw new Error('OpenAI API key not configured');
        }

        // Call OpenAI API for detection
        const detectionResult = await detectWithOpenAI(text, apiKey);
        
        res.status(200).json(detectionResult);
    } catch (error) {
        console.error('Detection error:', error);
        res.status(500).json({ 
            error: error.message || 'Internal server error' 
        });
    }
}

async function detectWithOpenAI(text, apiKey) {
    const prompt = `Analyze the following text and determine if it was likely generated by AI or written by a human. 
    Consider factors like creativity, nuance, personal experience, and stylistic consistency.
    
    Text: "${text}"
    
    Provide your analysis in JSON format:
    {
        "isAI": boolean,
        "confidence": number (between 0 and 1),
        "reasoning": string
    }`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            model: 'gpt-3.5-turbo',
            messages: [
                {
                    role: 'system',
                    content: 'You are an AI content detection expert. Analyze texts and determine if they are AI-generated or human-written.'
                },
                {
                    role: 'user',
                    content: prompt
                }
            ],
            max_tokens: 500,
            temperature: 0.1,
        }),
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`OpenAI API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    const resultText = data.choices[0]?.message?.content;
    
    try {
        // Parse the JSON response from OpenAI
        const result = JSON.parse(resultText);
        return {
            isAI: result.isAI,
            confidence: result.confidence,
            reasoning: result.reasoning
        };
    } catch (parseError) {
        // Fallback if JSON parsing fails
        console.error('Failed to parse OpenAI response:', resultText);
        throw new Error('Failed to parse analysis result');
    }
}
